### ISSUE TITLE
New Database Version Wipes the database 

### ISSUE THREAD

**Issue by rebelweb** [amuste/DnetIndexedDb#13]
We have successfully implemented this library in our project. Thanks You for your hard work. When we add a new field to a store it wipes the whole database. Is there a way to make it so the data is migrated and not deleted?

**Comment by amuste** [comment]
Hi. Thanks for using the library and for your kind words. I will look into it

**Comment by amuste** [comment]
The solution to this issue is in the Branch. 
Feature_20210104_Fix_Open_and_Upgrade

On Friday I will publish a new version. 

The changes are in this function:
https://github.com/amuste/DnetIndexedDb/blob/669371fe68cdbda68431b1271ed929d10ec4bb31/src/DnetIndexedDb/wwwroot/dnet-indexeddb.js#L117

**Comment by Kylar182** [comment]
> The solution to this issue is in the Branch.
> Feature_20210104_Fix_Open_and_Upgrade
> 
> On Friday I will publish a new version.
> 
> The changes are in this function:
> https://github.com/amuste/DnetIndexedDb/blob/669371fe68cdbda68431b1271ed929d10ec4bb31/src/DnetIndexedDb/wwwroot/dnet-indexeddb.js#L117

Update on this?

**Comment by amuste** [comment]
The new version is already uploaded with this problem solved
