### ISSUE TITLE
IndexedDbDatabaseModel could not be found

### ISSUE THREAD

**Issue by jon001** [amuste/DnetIndexedDb#27]
I'm sure I've missed something obvious because nobody else has raised this, but having installed the DnetIndexedDb 2.3.0 package in a Blazor (WASM) app I'm not able to resolve references to IndexedDbDatabaseModel, IndexedDbInterop etc. I was expecting the package to define these, and maybe it has but I've failed to find them so far.

To be clear, I've created a class deriving from IndexedDbDatabaseModel but the reference fails with the error "The type or namespace name 'IndexedDbDatabaseModel' could not be found", and Visual Studio doesn't suggest any "using" to fix it. The same problem arises if I attempt to derive from IndexedDbInterop.

I don't even see builder.Services.AddIndexedDbDatabase() as an option in Program.cs so if I didn't know any better I'd think I'd just failed to install the nuget package but I'm pretty sure I did!

I'd be grateful for any advice you can offer at this point.

**Comment by jon001** [comment]
Update: I had a look at Rich Bryant's very helpful repo here https://github.com/richbryant/FunctionalDatabase and noticed that he was using v1.0.1 of DnetIndexedDb so I tried downgrading and this worked - "using DnetIndexedDb" found your namespace and classes like IndexedDbInterop were available.
Upgrading to the next available version of the nuget package, v2.0.0-rc.1, broke the references again.
I'm still pretty much in the dark about the 2.x versions - is the usage radically different to the 1.x?
Thanks,
Jon

**Comment by amuste** [comment]
Hi @jon001. It is possible that the problem is in the following:

1.x versions are for .net core 3.x 
2.x versions are for .Net5

Anyway I am going to update the repo to include a WASM and Server Side test project

**Comment by jon001** [comment]
Hi @amuste, thanks for the tip - yes, that sounds right. My blazor app is targeting .Net Standard 2.1 which I believe means it's using .Net Core 3.0 in reality. 
The package is working nicely at v1.0.1 right now and I was going to carry on with that but your comment inspired me to wonder why my app wasn't targeting .Net5 so now I've converted it and it's broken.
At least I know which package to use when I manage to fix it though :-)

Looking forward to seeing your WASM demo in the repo.

**Comment by jon001** [comment]
This probably won't surprise you but I can confirm that the v2.3.0 package is working fine now I've upgraded the Blazor WASM project to .Net5. I'm glad you brought this up - there are a lot of advantages to upgrading but the upgrade process is still a bit raw and had escaped my notice until now.
