### ISSUE TITLE
Bug: Could not add new object store to existing database.

### ISSUE THREAD

**Issue by noelrv** [amuste/DnetIndexedDb#29]
By setting a higher version of the database, the old database is upgraded to a new version. New object stores that are declared for the new version should be created, This is not happening.

**Comment by noelrv** [comment]
Fix applied in version 2.3.1.

**Comment by bgriffy** [comment]
Could you show an example of this working? I'm still having issues. The only way I'm able to add a store to an existing DB is by deleting the DB first.
