### ISSUE TITLE
Question about adding stores

### ISSUE THREAD

**Issue by bgriffy** [amuste/DnetIndexedDb#33]
I've noticed when you first add a store to your model, you will get an error if you try to get data from it without writing to it first. 

It would be nice if an empty store was created when the page loaded so it didn't error out when trying to fetch from it. 

Would this be possible? Or is this functionality already there?

**Comment by noelrv** [comment]
You are missing something.

Check if you have issued OpenIndexedDb() before the read.

**Comment by bgriffy** [comment]
Thanks for the response. You were right, I was missing something. Basically, my code was automatically pluralizing the name for the store. Name of the store should have been "Equipment", but it was getting stored as "Equipments", hence the error when I tried to read as "Equipment". 

User error, please disregard! Lol.
