### ISSUE TITLE
Is there any way to query for true/false conditions?

### ISSUE THREAD

**Issue by thepra** [amuste/DnetIndexedDb#36]
Given that I would like to use the IndexedDb for caching files for offline use I was wondering if I could in any way query for the presence or absence of records base on their key.
Is there any way?

**Comment by amuste** [comment]
Hi @thepra 

bool is not a valid Key value. 

check w3c:
https://w3c.github.io/IndexedDB/#key-construct

**Comment by thepra** [comment]
I mean like in a Linq query:
`bool isRecordPresent = await  indexedDb.AnyAsync(record => record.Key == providedKey);`
My key is still a valid unique string.

**Comment by amuste** [comment]
You can not query in that way. What you can do is get the record by its key.

https://github.com/amuste/DnetIndexedDb/blob/2e175c4f91549d670a67e3e7917d083b823f3aa6/samples/ServerSide/Pages/Index.razor#L64

**Comment by thepra** [comment]
So it's not possible, my case is that getting a single record of up to 2MB is waaay too much of a performance hit for the sole purpose of figuring out if a record with a certain key exists. Thanks for the clarification.

**Comment by Kylar182** [comment]
> So it's not possible, my case is that getting a single record of up to 2MB is waaay too much of a performance hit for the sole purpose of figuring out if a record with a certain key exists. Thanks for the clarification.

You can query by int / Enum types. I created a True / False Enum because I was having the same issue.

`{
  /// <summary>
  /// Replaces a Bool with it's String Version
  /// </summary>
  /// <remarks>
  /// Used to Speed up Queries by Indexing Booleans for IndexedDB 
  /// </remarks>
  public enum BoolReplace
  {
    /// <summary>
    /// False Boolean (0)
    /// </summary>
    [Display(Name = "False")]
    False = 0,
    /// <summary>
    /// True Boolean (1)
    /// </summary>
    [Display(Name = "True")]
    True = 1
  }
}`

**Comment by thepra** [comment]
@Kylar182 And could you also show how do you use it precisely?

**Comment by Kylar182** [comment]
> @Kylar182 And could you also show how do you use it precisely?

```
    public virtual async Task<List<T>> GetNotSyncedAsync()
    {
      List<T> notSynced = await _database.GetByIndex<BoolReplace, T>
        (Table, BoolReplace.False, BoolReplace.False,
            nameof(OfflineBaseModel.Synced).ToCamelCase(), false);
      return notSynced.Where(q => q.InUse == BoolReplace.True).ToList();
    }
```

This is how I used it in one of the queries.

**Comment by Kylar182** [comment]
I have a largely Generic Repository Pattern system with inherited Generics.

**Comment by Kylar182** [comment]
```
    /// <summary>
    /// Converts Boolean to Enum for Faster IndexedDB operation
    /// </summary>
    public static BoolReplace FromBool(this bool convert)
    {
      if (!convert)
        return BoolReplace.False;
      else
        return BoolReplace.True;
    }

    /// <summary>
    /// Converts Nullable Boolean to Enum for Faster IndexedDB operation
    /// </summary>
    public static BoolReplace? FromBool(this bool? convert)
    {
      if (convert == false)
        return BoolReplace.False;
      else if (convert == true)
        return BoolReplace.True;
      else
        return null;
    }

    /// <summary>
    /// Converts Boolean to Enum for Faster IndexedDB operation
    /// </summary>
    public static bool ToBool(this BoolReplace convert)
    {
      if (convert == BoolReplace.False)
        return false;
      else
        return true;
    }

    /// <summary>
    /// Converts Nullable Boolean to Enum for Faster IndexedDB operation
    /// </summary>
    public static bool? ToBool(this BoolReplace? convert)
    {
      if (convert == BoolReplace.False)
        return false;
      else if (convert == BoolReplace.True)
        return true;
      else
        return null;
    }

    /// <summary>
    /// Converts Boolean to Enum for Faster IndexedDB operation
    /// </summary>
    public static bool ToBool<TValue>(this TValue convert)
    {
      return bool.Parse(convert.ToString());
    }
```

Here's some static Boolean conversion methods.

**Comment by thepra** [comment]
@Kylar182 ok, now I'm a little bit confused, how does your model system looks like in this case? Do you have a table with (key,value) for the booleans and another (key,value) table for the actual data?

**Comment by Kylar182** [comment]
> @Kylar182 ok, now I'm a little bit confused, how does your model system looks like in this case? Do you have a table with (key,value) for the booleans and another (key,value) table for the actual data?

No, it's  the same table. You can index properties in any table, in this case I indexed a BoolReplace Property on these models. The query shows how to query using that BoolReplace index and variable..
