### ISSUE TITLE
reopenning a deletedabase

### ISSUE THREAD

**Issue by mikemoore13** [amuste/DnetIndexedDb#42]
i got an error when i try to open a deletedb

Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

IndexedDbStorage.DeleteIndexedDb()
IndexedDbStorage.OpenIndexedDb()

**Comment by Kylar182** [comment]
> i got an error when i try to open a deletedb
> 
> Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
> 
> IndexedDbStorage.DeleteIndexedDb()
> IndexedDbStorage.OpenIndexedDb()

I think this was fixed but was never pushed to the nuget packages along with some other fixes.

You should be able to fork the library on your own and use that.

**Comment by Kylar182** [comment]
> i got an error when i try to open a deletedb
> 
> Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
> 
> IndexedDbStorage.DeleteIndexedDb()
> IndexedDbStorage.OpenIndexedDb()

https://github.com/amuste/DnetIndexedDb/pull/37
