### ISSUE TITLE
Is the NuGet package outdated?

### ISSUE THREAD

**Issue by stephajn** [amuste/DnetIndexedDb#50]
Just looking at the samples to get going, and there's no method on the IndexedDbDatabaseModel that uses Generics to add a model class to the store. I looked at it using JetBrains Decompiler and can confirm there's no method.  But when I looked at the source code in this repository, I can see it is there.

I have Version 2.3.1 of the Nuget package installed.

**Comment by amuste** [comment]
Yes, was outdated. I just released version 2.4.1, which contains those changes.
