### ISSUE TITLE
Could not load content for rxjs.umd.min.js.map HTTP error 404

### ISSUE THREAD

**Issue by fseffert** [amuste/DnetIndexedDb#7]
I got this alert from the browser console, when I'm starting up my Blazor WebAssembly App:

![image](https://user-images.githubusercontent.com/12700143/99159629-52e0ee00-26de-11eb-80a8-a2d41173d588.png)

**Comment by amuste** [comment]
Hi. I will add it in the next release. But it is not necessary at least you want to debug rxjs in production

**Comment by amuste** [comment]
Hi. Fixed
